//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CityMaster
{
    public int Id { get; set; }
    public string City { get; set; }
    public Nullable<int> State { get; set; }

    public virtual StateMaster StateMaster { get; set; }
}

public partial class Dealer
{
    public Dealer()
    {
        this.Registrations = new HashSet<Registration>();
    }

    public int Id { get; set; }
    public string DealerName { get; set; }
    public string MobileNo { get; set; }
    public string EmailID { get; set; }
    public string Address { get; set; }
    public Nullable<int> City { get; set; }
    public Nullable<int> State { get; set; }
    public Nullable<int> RTO { get; set; }
    public Nullable<int> LoginID { get; set; }

    public virtual Login Login { get; set; }
    public virtual RTO RTO1 { get; set; }
    public virtual ICollection<Registration> Registrations { get; set; }
}

public partial class Login
{
    public Login()
    {
        this.Dealers = new HashSet<Dealer>();
        this.RTOes = new HashSet<RTO>();
    }

    public int LoginId { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string Role { get; set; }
    public Nullable<bool> IsActive { get; set; }

    public virtual ICollection<Dealer> Dealers { get; set; }
    public virtual ICollection<RTO> RTOes { get; set; }
}

public partial class Registration
{
    public int RegId { get; set; }
    public string RegistrationNo { get; set; }
    public string TempRegistrationNo { get; set; }
    public Nullable<int> DealerID { get; set; }
    public string Owner { get; set; }
    public string Address { get; set; }
    public string Mobile { get; set; }
    public string Email { get; set; }
    public string Manufacturer { get; set; }
    public string Vehicle { get; set; }
    public string ChasisNo { get; set; }
    public string Engine { get; set; }
    public string color { get; set; }
    public Nullable<System.DateTime> RegistrationDate { get; set; }
    public Nullable<System.DateTime> ValidUpto { get; set; }
    public string Status { get; set; }
    public Nullable<int> RTOId { get; set; }

    public virtual Dealer Dealer { get; set; }
}

public partial class RTO
{
    public RTO()
    {
        this.Dealers = new HashSet<Dealer>();
    }

    public int RTOId { get; set; }
    public string Name { get; set; }
    public string MobileNo { get; set; }
    public string LandlineNo { get; set; }
    public Nullable<int> City { get; set; }
    public Nullable<int> State { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<int> LoginID { get; set; }

    public virtual ICollection<Dealer> Dealers { get; set; }
    public virtual Login Login { get; set; }
}

public partial class StateMaster
{
    public StateMaster()
    {
        this.CityMasters = new HashSet<CityMaster>();
    }

    public int Id { get; set; }
    public string State { get; set; }
    public Nullable<bool> IsActive { get; set; }

    public virtual ICollection<CityMaster> CityMasters { get; set; }
}
