//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int RegId { get; set; }
        public string RegistrationNo { get; set; }
        public string TempRegistrationNo { get; set; }
        public Nullable<int> DealerID { get; set; }
        public string Owner { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Manufacturer { get; set; }
        public string Vehicle { get; set; }
        public string ChasisNo { get; set; }
        public string Engine { get; set; }
        public string color { get; set; }
        public string RegistrationDate { get; set; }
        public string ValidUpto { get; set; }
        public string Status { get; set; }
        public Nullable<int> RTOId { get; set; }
    
        public virtual Dealer Dealer { get; set; }
    }
}
